### ISSUE TITLE
Rotation Property Doesn't Work

### ISSUE THREAD

**Issue by kturnal** [delight-dev/Delight#38]
When I use the Rotation property, the input is supposed to take a Quaternion as an argument, but it takes 3 arguments. Also, when I type in a Vector3, it is converted into Quaternion before it is transferred into Euler angles again.

Here is an example:
```
<Button Rotation="90,0,0" />

turns into:

Delight.Button.RotationProperty.SetDefault(_mainMenuViewScrollUpButton, Quaternion.Euler(0.7071068f, 0f, 0f));

```
So the input is getting converted along the way somewhere. `Quaternion.Euler(90,0,0,0)` returns `Quaternion(0.7071068f, 0 , 0 , 0.7071068f).` , which is already the input here but also takes into account the first three variables.

**Comment by patrik-u** [comment]
Thanks for your bug report. It is supposed to take Euler arguments in XML and then convert them to Quaternion, but there was a bug in the value converter *QuaternionValueConverter.cs* that I fixed in a commit. Now if you specify `Rotation="0,0,45"` it will rotate the view around the Z-axis (probably the default type of rotation you want).

https://github.com/delight-dev/Delight/commit/9c0cfa5d62f7a0bde097a0b6db9f0aa974bbb3be
