### ISSUE TITLE
How to remove a view?

### ISSUE THREAD

**Issue by sommmen** [delight-dev/Delight#5]
Hi,

When you press 'Create view' whilst in the /content/views folder it keeps reloading, which means you cannot give the file a proper name.

Doing create view in any other location works correctly.

This however led me to create a view called 'Ma' - how do i properly remove this view? i tried deleting the files .cs/.xml/.g.cs but that keeps giving me errors, since then it cannot vind the class in viewactivators:

`            ViewActivators.Add("Ma", (x, y, z) => new Ma(x, y, null, z));`

Refreshing unity keeps adding above line...

**Comment by patrik-u** [comment]
The reload issue seems like a bug because it should work the same in all
view directories. You can reload all views after removing the .xml/.cs
files, by pressing the "rebuild all" button in the delight editor window
(this should be done automatically if you remove the xml while the editor
is running) .Then it should remove all the generated activators for the
view.







Den sön 15 mars 2020 kl 17:57 skrev sommmen <notifications@github.com>:

**Comment by patrik-u** [comment]
[Menu to open delight editor window](https://ci6.googleusercontent.com/proxy/UGVHG3-bX0v_ml744AJcZK8WJyoPuYRVSaePmFaTltP05nLQcFuvqwopir8zRkG02O-9WjAo6yl8DHdaBwB2DembUnQsGIDC4MuWIjP5xpdXUux-jjY4=s0-d-e1-ft#https://delight-dev.github.io/Tutorials/migration-delight-window.png)

[Reload button](https://ci6.googleusercontent.com/proxy/LoE23a7VJZaplqP4Rt-d7kt7Zv0LJN9YWDafCs9DmUnrXbmNS5UrupBMDfA7XvSZ4MppqyPERPQ44epvThGttd-4iecUYtpNNxGSqKAUK2bHQHaZvW3KSw=s0-d-e1-ft#https://delight-dev.github.io/Tutorials/migration-delight-window2.png)
